creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    # Use this age recipient to encrypt tenant secrets.
    age: age1jfycz720jlzt3ycem57ltlmmh6fvndjyjhwskd0732ajuqg5k4vqfafyc3