"""initial

Revision ID: 5620a60df499
Revises: 
Create Date: 2026-03-11 14:12:04.895855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5620a60df499'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flag",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("app", sa.String(), nullable=False),
        sa.Column("env", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flag")),
    )
    # create unique constraint matching SQLModel UniqueConstraint("app","env","key")
    op.create_unique_constraint("uix_flag_app_env_key", "flag", ["app", "env", "key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_flag_app_env_key", "flag", type_="unique")
    op.drop_table("flag")
    # ### end Alembic commands ###