apiVersion: v1
kind: Secret
metadata:
    name: feature-flags-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:5LNheC5fXR0=,iv:xY7H3CDTtNQ2lLdB8Hpc4aAKVppGAtvYVHQ0J3fhrK4=,tag:YadCKfxSFpXzJSsR4SBGJQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:U0db+AboJOM=,iv:YnBcyYB/rQHNUNR2TdP9PJqV0ttKd+ca6Ke5jTmNawo=,tag:p9fjALRf2F4VZF/LErwLPg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:LYlR2oP+RhY1XJmODp/xf88+Q4OWg6PAUPtnFr5xH3M36CKly1KW3jnwSw6s7X8gvTwn+QDojCb/R0HPS1HQYhl5538vow==,iv:RVB/2FqLR239Q5hkG+SPn1fHVz6OCwvuxK27wXaCSdQ=,tag:HdF0CdcONRrUKzI3epouAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jfycz720jlzt3ycem57ltlmmh6fvndjyjhwskd0732ajuqg5k4vqfafyc3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZEpKS0pBemVCU2FnY0M5
            TzF6SFV0a2tuSStHc1dQQm04QnlEWkpLeFNvCnArdWIxQmV6M0NaV2o4dUl4dUkw
            YXo1cHJSNE14OVovQTZhaVRpK1ZKMVEKLS0tIFRxRjQvd25qZnErMGFWVjVtU1ZW
            YWVEZExlT0JLZDQ2VE4yQkNPT0Q3bzgKvuY6Ip1eHC9OTfQZR1Idqsxfuya4Tstd
            vmSduB+sVoNP4zJ9PC3cs5bpnDJQfNvFK6Wu2+EwwSHj4jSyOQ5bfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T18:27:17Z"
    mac: ENC[AES256_GCM,data:yDqEAaoPDXxaB2OuZJfrwsau4gnQNk6pueUKL8x1A25TyOqD17DCU5AHo6xYorCy9JQPuvkvXHD/1PRs5fMZm790BF4OyqMCFf9RSh36AvWHIrYOXuVeIbVmdKgDR7w+lK1srwJ8ah8GfnACRodYoef/Wjd28TAzUhKS9i64wPc=,iv:q5O2IHvq+rzQieFi6+AS1MkmJhCY8pZLryPg14GFCTw=,tag:gv/1V02kC/xBic0Fgh/zSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
