apiVersion: v1
kind: Secret
metadata:
    name: feature-flags-secret
    namespace: feature-flags
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:0z3I7EVObao=,iv:WOEdS6yLbgYw55jDwJaNOiADCzUPtjZwuu7Bk8Nh0A8=,tag:NOxUf7TQVBTyJLyUsp352Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Zp4zEvL6hgI=,iv:Ru3VDbbH0JQRGv1OZBdOZp4wUocrsRQzRst0iAY206w=,tag:3g1rg5Z2T510pOHqr87PWA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:jgh1mVE1wLyXWEMah5/gU6/EgH2SyH6pgvAD805yUt2sCOFAUNUbB1yNIuZRj+fTC5kH6yE6rLt1ONG2PUNwdO0N3gEJgQ==,iv:VdSA5snMjBjBF3sb6VgK/3ByPoShh+232dSnINF90HI=,tag:ePOpWD4VRcvVwk3Ga2SehA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jfycz720jlzt3ycem57ltlmmh6fvndjyjhwskd0732ajuqg5k4vqfafyc3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ1NKU05Bd0VkajJIUk9H
            bklTRDJ2dG9IRnZrNGZQQUszb1JDRlVYNEc4CmJKKytqTE5Cd0laNWk4WEk2YkVp
            bUFIczkxRmZhNUF1TjUxRC9wTGRaVzgKLS0tIDdKSkkxemlTb05DOWN0cUJySUlH
            QkxnOTJjTFQ4YmNOb0R5dWJLb1I3eUUKX4OZf1TSJ0e/7r52UgWyAB37zdNqS663
            LbzvQHwCZFqG2zk6HB9v5XX+sfVCXuGd8nUPBKsqdt/F33N+boTWzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T18:05:17Z"
    mac: ENC[AES256_GCM,data:TCiIFw0Y38dxL2IFsuwVucN+kHyYrtSAKCzLH99P5Q5kOa203HEI+X+F+YFK59KtmKYJXf2u0tl3s5ua+MWwHLL413RxS3NwsaOnI+TP4OZdHquegFx1tBvDQNUzdDd/AujZyz8tXtp2/asI8AzB6wTjCN8GcIpiHRdrwH1e3Zo=,iv:1m7B3bbHSLcBWCXHVIgmxcVRcoRlpNqEzp/JBvDDWFE=,tag:gEAblCR70qEeadGyiqF1+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
