apiVersion: v1
kind: Secret
metadata:
    name: feature-flags-secret
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:MRYZMVNRhWob,iv:lnIhmstBpouipKyf/I2tVR6GOMqBVfJgPn5Hc8wkaQ8=,tag:8+NlRYqkLRyZKWRZn6a3Cg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Wm9pGBwhmIM=,iv:ryubnqdtaySbvuB6jUCwd4vv0GsMp2nn1ocW7w2MMMc=,tag:gl/DBa/zep0CzMEtNN+PFQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:EIFPLXf4LTOq+63qaR7eexcgCXZWt9MJyiqqsLXrXa3m6jx8C0x/Wa90fpw/3Z5paLT8DnQDYovyrV4Ix9OLNiTYMrC7EA==,iv:b9tlcdRSK6wn9Y/kbKgC8QE6GDBqnKOGCLYwmFE4Hv4=,tag:nXuBiaaNSbOoETwEOHHV+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pnuww2scf43dlqwutf73qz4d4pzdu54gvarnvpr524n6g2waysasxsla60
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRckRjbEQra05ZazVoeC9I
            ZmRCdlRRWWN5RUQvNUZRZUNWVVVxQit3aVRzClRqTHZQUDZBYVUzUGJGaHlYZGU0
            SkczVGZ4NU1uQ2hISkhEMGZBZm1peE0KLS0tIGVUeDFsUXRJUEtSVjM3R3M1YXR5
            K0l5eExlWTE5aUJlQXBLbjRSaXpNbUkKv0yubF++X/Fp+vlmECSoC9+a5K9Of2Af
            JiOy5w755kDPTKXXL3AOF1BY8KKAy7SJyRMo3EbqrrXVM5HXZNtW/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T08:21:17Z"
    mac: ENC[AES256_GCM,data:HQZfVcFVPHYsEJQVV1x56B+D2u6YAxZz2MkwJolocnwixnxG+ZfCDXtUh4e306bOgIaf3ocISgE6GxOmz9J10hyHW665UQVOkvDfHDCqSwKjRyPQ+aRe8FRDr00h+4H/gUliRsfEAN5FKxccsInnqEkOAwTXrviOBnk/dEezfNo=,iv:zjZamKmCtbnZNHSw0eZOubtyPfsXf7aKKBzjgh8JTw8=,tag:QELjRcqYoXDP4elueFQEmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
