apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ADjhj/2orqmzE8eJQ47/rY/21ifUYhQgGrWzRCqA504jNDjm/jRrGLVZDaVSGfmYRnNdDRopd1An5/4vCTPVKJvOMB7Mt5nh6D9/WeNCKiqCRdvV/mqhzIY7t4Ll3D4B5KO36jvNkks+0m3Vs2EE5eDpRrmhq4MPqFbU0gy+nRzkKahP5FhR7Ycj1ShfpbrbXk1V1UXzhO/9QWQ2DyFdFIxeWOqqzXVqQKPe2JXJnbndP26ZHl9n6gnqs3P7pliAss9nWY38SrvumO5HL15akxGzS2rioemboWFliIDPGI0k3Bgs/eCJyV3hwVE=,iv:P1kG6WgW0+unrvi6yOfVz59MED9HSNG4D9/EZG4XuR4=,tag:HfIljAF/Fqq0VLZW73v+8A==,type:str]
kind: Secret
metadata:
    name: ghcr-credentials
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jfycz720jlzt3ycem57ltlmmh6fvndjyjhwskd0732ajuqg5k4vqfafyc3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK20xUGxxQ25KYk9Fc1BN
            RWRyUjhUaTh4a29SRWZKZ1UvLzdDTzVDb0NnCko0bUIrLyt2akhhbjJNQjFyRWdB
            c01YQWtwSk5rNnV5VzhxU0htcDM3V1UKLS0tIG9zWGVmdFN6WVlPSy9sOUREdTVs
            TlpIbTdZWStTa2JTWWcwSFBSUFpINjgKpqr1+ZpgDwMWPlsPRsWjuJm0ozdcD87p
            i/+VxIC69P8zrd7EWNMEXNl9R2DTPz0ze9Zo1pyXsfARSulH8OEzUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T10:35:52Z"
    mac: ENC[AES256_GCM,data:4sMCpHx6eOfNO521P3GYGTYDeVK5GSIditoXczv10kNecj8dKHsPCDRDLDxJrPW1ZFbqecBiU3FpUlxlAtIFIZZRxJTS96eV39aO0ckKDpRYAfr+06scZp0paAmj2ZQ2mY3iodwFgfDs4X3e30xk3K8O0t0GoumMs9aRJm3eEjc=,iv:krmgwq7y2LsmRCUWpn5ZtiyIWQ7/vnFoHbZ90kKjQyc=,tag:EGVg7btJpALSngj5XNylsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
