apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:mQsqBoqd3ZH/mM4o3WwRCxFewQ1XjlWbqDK91RXlNKtSL/SO2fqYBtjN8jdYrY6HN8ssek84uT1ah6Riebla12B22zjlhMRWSRaBWoFo9jt/ui6OxQiz/kt5BE4Lo7vgRqQU,iv:9xZS6k6OZfsen6twPXk1s0hmbFjP+auWVB2tTluGkTY=,tag:jrrivj2sq3yo1u0tc21ykg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pnuww2scf43dlqwutf73qz4d4pzdu54gvarnvpr524n6g2waysasxsla60
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveWRhVW82bTBCaE5VVFpL
            N3BWVklMMGxwWUNFSnF0a1JmbDZUNURUR1U4CmRqdUtYZGg2cFBFSkVwN2JIbGoy
            WkJMN2FLZjRFNnh2SU95MHM2WVZRMFUKLS0tIDBzcDUra3cyZEV5SXk5cDJCY0xl
            cC9iMFVYVWxFa2w3TkRISDN2VXoyeEUKTrvth1GnKAB9Aty7e9FwrGs6Q/zC07xf
            80TBEdnMZp9yT+M10/QH14wZKZPSmKjgchE7M5RiOO0Fjj5UAVZpdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T08:28:42Z"
    mac: ENC[AES256_GCM,data:prZ42x7m9XNXs5AcYgdqMih3O++4bFYTdCwToJ7Slwbu6m0RC/UDAx0rZ1bDFRqqnhRCOvlsT1DA43whWAGWCZ30r1FiHq5lK9JoYcCWJNQNRMNAnmxDt3U1aBhCeWoG/13TqKjzgczVWnv0B/1GWyAnT4aLaOXhgSgUs5kou1A=,iv:8ErPwxe+w/9iA0RH0oPK3gxs3/wGq02u4BaWT6PNi4U=,tag:e/NR1LrhxDe25P0c46A/sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
