apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:MrI529kEtbf5giQqzK26jVWPOKVtDvnTD2bujHpJtQLwWP7mpSENMQ7EZMB53jo8RKWq4vA3yjz0R/+fQh6ofakMCuxsoiklu6LnC3kxIH0IU2tN9dh2doByRuKhERxoF8qQYNm0pm+/zX/0acD7KzAGxWuQ7Ddqf1xFTs7fU4XvLDpgH+XbMQ==,iv:pejXlQfl0FuhCAFBkZ0ZnIUGvwmgiMANQHpgDAay5KA=,tag:no8VU+v5mY72CpkUhE3u4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jfycz720jlzt3ycem57ltlmmh6fvndjyjhwskd0732ajuqg5k4vqfafyc3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaTkxWXJETFlzQTJlWmtq
            cW9uYkZMbmJwU3BxQnRETDc4VVZjZVRBRGcwCmJNREkyQmZsMEowWHgzN3ppNWVE
            cnlqeDZ6bURmYkxUY203TnQ3dk5NT28KLS0tIFh5cGZnMy9RSnpxTUlMYnFXTUta
            ZjlvZmtjY2c0U2xDelh2UnRCUkpMWGcKABybrI+dP6G/Z1aeqofW/LLBquuTn7Ky
            5S89UOe8nVcs5zLmAl2T8q0ER105OYkVAazpSlqvekFxTOQElOt+Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T10:20:32Z"
    mac: ENC[AES256_GCM,data:iuTd00oPrU7qxfOv1dGciNKj0lk9ERUb7P8OQ5aZ2ayi64JiU6P1BerAagOIxvk+eAyWzw8dn4ObGQ8LvDeXnSuNQpYzPXAfu0Gi5hC/Mc1mdZfngo5QDvbw22OskQgj8mxCcYKsN8OmYyS9rvSNccqvNMZb/HI+Oc7wczN1Wd0=,iv:d1fW+zSyXe7kYXgbl1BSvtooOQ7Kov4RnK3gIA1fWkY=,tag:/ukI2r471vgaZT33DnQJug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
