apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml

patches:
  - path: patch-frontend-svc-loadbalancer.yaml
  - path: patch-image-pull-secret-api.yaml
  - path: patch-image-pull-secret-frontend.yaml
  - path: patch-configmap-dev.yaml
    target:
      kind: ConfigMap
      name: feature-flags-config

images:
  - name: ghcr.io/pmiloszz/feature-flags-api
    newTag: sha-decebf
  - name: ghcr.io/pmiloszz/feature-flags-frontend
    newTag: sha-decebf