apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: configserver
        static_configs:
          - targets:
              - feature-flags-api-svc.feature-flags.svc.cluster.local:8000
        metrics_path: /metrics
