apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags-config
  namespace: feature-flags
data:
  ENVIRONMENT: "prod"
  DEBUG: "false"
  USE_ALEMBIC: "true"
  POSTGRES_USER: "configserver"
  POSTGRES_DB: "flags"

