apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feature-flags-ingress
  namespace: feature-flags
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - feature-flags.example.com
      secretName: feature-flags-tls-prod
  rules:
    - host: feature-flags.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feature-flags-svc
                port:
                  number: 80

